version: '3.8'

services:

  postgres-14:
    image: postgres:14.5
    restart: always
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - ./.env
    volumes:
      - ./init_user_db.sql:/docker-entrypoint-initdb.d/init_user_db.sql

  web-server:
    build: .
    command: bash -c "cd /code/src && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080"
    ports:
      - ${PORT}
    env_file:
      - ./.env
    depends_on:
      - postgres-14

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:root
    depends_on:
      - web-server
    ports:
      - ${NGINX_PORT}