"""id_fields_id_uuid

Revision ID: 9d6fbb088b95
Revises: 4ee7ec7ac3dc
Create Date: 2023-02-28 17:27:28.336711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6fbb088b95'
down_revision = '4ee7ec7ac3dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
